### ISSUE TITLE
SAML SSO Integration

### ISSUE THREAD

**Issue by TingWeiLun** [ASUS-AICS/DeveloperGuide#9]
We need to enable SAML SSO for our GitHub organization ASUS-AICS

**Comment by TingWeiLun** [comment]
I gathered GitHub support and our MIS team to discuss about the settings issues the Tuesday (2019-02-19). But Xavier could not help us and told us to open a GitHub support ticket.

GitHub ticket link:
https://enterprise.githubsupport.com/hc/en-us/requests/79098?page=1

**Comment by TingWeiLun** [comment]
Finally, we passed the SAML configuration test today (2019-02-22). But our colleagues still cannot log in with ASUS account successfully. I left tons of screenshots and messages to the GitHub support page and hope that can help them to figure out what's wrong.

**Comment by MistLiao** [comment]
I saw notification that asked me to do SSO authentication and I login with my OA account. How do I know it works or not?

**Comment by TingWeiLun** [comment]
Hi @MistLiao 
GitHub hasn't responded since last Friday.

For now, I don't recommend to do the SSO since it might cause some issues after your SSO session expired. I'm still working on this one with GitHub and MIS.

**Comment by TingWeiLun** [comment]
GitHub not responding.
We might need to start our Enterprise Server trail or ask for MIS if they can help to test different configuration combination. (MIS說這是盲測，但還是要問看看他們願不願意幫我們試試看幾種不同的設定組合，說不定會有進展？)

**Comment by whelan957** [comment]
Updates:
1. GitHub support starts to answer our question again today. 
2. First thing back on track is to ask them to disable SAML for us for now.
3. Thanks to Adam, we got our Enterprise Server trial extension to March 16th.
4. We got three possible endings in this: 
    1. We give up SSO and let everyone come in by invitation.
    2. We use Enterprise Server and go LDAP. We need to bare extra fee for our machines on Azure for this one.
    3. We magically fix this SAML issue.

**Comment by whelan957** [comment]
GitHub support said he can do a Zoom session with us to figure out the SAML configuration together.
I'm asking MIS to confirm the meeting time slots and would sync with GitHub ASAP.

**Comment by whelan957** [comment]
This problem is fixed!
Hooray!

Complete conversation can be found here. https://asus.sharepoint.com/sites/AICSSoftwareEngineeringSystem/Shared%20Documents/General/SAML%20SSO%20settings%20%E2%80%93%20GitHub%20Enterprise%20Support.pdf

**Comment by whelan957** [comment]
This issue is fixed.
